name: Release

on:
  release:
    types:  [ created ]

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
      packages: write

    env:
      GRADLE_OPTS: -Dorg.gradle.caching=true

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Set environment for version
        run: long="${{ github.ref }}"; version=${long#"refs/tags/v"}; echo "version=${version}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - uses: gradle/actions/setup-gradle@v3

      - name: Release maven artifacts
        run: ./gradlew -Pversion=$version publish
        env:
          ORG_GRADLE_PROJECT_GitHubPackagesUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_GitHubPackagesPassword: ${{ github.token }}

      - name: Create docs
        run: ./gradlew dokkaHtmlMultiModule --no-configuration-cache
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/dokka/htmlMultiModule
      - name: Deploy Documentation to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
